### ISSUE TITLE
Create a semantic version release

### ISSUE THREAD

**Issue by dietmarw** [denistwo/FeedDriveLibrary#1]
In order that this library can appear in the package index https://impact.github.io/ it needs to have a release with a [semantic version number](http://semver.org/). The simplest would be to generate a start release and tag it `1.0.0`.

**Comment by denistwo** [comment]
done

**Comment by dietmarw** [comment]
Great. Only last bit the tags and release names are quite misleading. Probably rename `01` to `v0.1.0` and `2` to `v0.2.0`. Rename means normally creating a new tag and deleting the old one.

**Comment by denistwo** [comment]
I deleted the earlier releases. I do not think they are helpful for anyone.

Thanks again for your great help! I think by now, I learnt the basics of github.

---

Von: Dietmar Winkler notifications@github.com
Gesendet: Sonntag, 25. September 2016 18:34
An: denistwo/FeedDriveLibrary
Cc: Özdemir, Denis; State change
Betreff: Re: [denistwo/FeedDriveLibrary] Create a semantic version release (#1)

Great. Only last bit the tags and release names are quite misleading. Probably rename 01 to v0.1.0 and 2 to v0.2.0. Rename means normally creating a new tag and deleting the old one.

##
