### ISSUE TITLE
Use ASCII only in your library

### ISSUE THREAD

**Issue by dietmarw** [denistwo/FeedDriveLibrary#2]
Using non-ascii characters just causes problems with the encoding. 

E.g., use `&Ouml;` instead of `Ö` in the HTML parts.

**Comment by denistwo** [comment]
Issue solved. I guess my surname made the problem ;)

**Comment by dietmarw** [comment]
You should look for other umlauts before closing this one. Simply do a text search for ä.

**Comment by denistwo** [comment]
Thanks. But that is what I did.

I just double-checked. Text search of the "mo-file" does not find any "Umlaute" in the text.

I really doubt my sanity now ;)

---

Von: Dietmar Winkler notifications@github.com
Gesendet: Sonntag, 25. September 2016 16:58
An: denistwo/FeedDriveLibrary
Cc: Özdemir, Denis; State change
Betreff: Re: [denistwo/FeedDriveLibrary] Use ASCII only in your library (#2)

You should look for other umlauts before closing this one. Simply do a text search for ä.

##

**Comment by dietmarw** [comment]
A quick check gave:

```
FeedDriveLibrary.mo
1163:        "Model of angular velocity dependent friction losses according to Gross, Hamann and Wiegärtner (2006)"
1644:        "Model of a ball screw drive according to Gross, Hamann and Wiegärtner (2006). Can be parameterized by typical supplier data such as from A. Mannesmann"
```

**Comment by denistwo** [comment]
Thanks!

Now I understand the problem. Notepad shows me this as:

WiegÃ¤rtner

No wonder, text search did not work.

I will sort this out.

---

Von: Dietmar Winkler notifications@github.com
Gesendet: Sonntag, 25. September 2016 17:30
An: denistwo/FeedDriveLibrary
Cc: Özdemir, Denis; State change
Betreff: Re: [denistwo/FeedDriveLibrary] Use ASCII only in your library (#2)

A quick check gave:

FeedDriveLibrary.mo
1163:        "Model of angular velocity dependent friction losses according to Gross, Hamann and Wiegärtner (2006)"
1644:        "Model of a ball screw drive according to Gross, Hamann and Wiegärtner (2006). Can be parameterized by typical supplier data such as from A. Mannesmann"

##

**Comment by dietmarw** [comment]
As a tip, especially when dealing with text files and encoding. Get yourself https://notepad-plus-plus.org/ 
notpad is unfortunately a rather bad text editor.

**Comment by denistwo** [comment]
Thanks...of course I am already using notepad++ ;)

Probably the commits and updates from the repository corrupted the umlauts in the file.

I solved the issue by searching in an earlier version of the library to find out about the occurences.

---

Von: Dietmar Winkler notifications@github.com
Gesendet: Sonntag, 25. September 2016 17:41
An: denistwo/FeedDriveLibrary
Cc: Özdemir, Denis; State change
Betreff: Re: [denistwo/FeedDriveLibrary] Use ASCII only in your library (#2)

As a tip, especially when dealing with text files and encoding. Get yourself https://notepad-plus-plus.org/
notpad is unfortunately a rather bad text editor.

##

**Comment by dietmarw** [comment]
The problem is normally always the encoding. Modelica files should be either (preferably) ASCII only or UTF8. Now Windows like to save stuff as Latin1 which then will convert the non-ascii umlauts to something different. Hence, stick to ASCII and you are trouble free. And since HTML supports entities you can still have all the special characters :-)

**Comment by denistwo** [comment]
Thanks again for your helpful comments. Now I am ready for the new release :)
