### ISSUE TITLE
Update/correct the license information also in the library 

### ISSUE THREAD

**Issue by dietmarw** [denistwo/FeedDriveLibrary#4]
Once it's corrected in the README you might want to correct it also in the library itself. Also your repo should contain the license text, e.g., by putting a [LICENSE](https://github.com/dietmarw/MITLicense/blob/master/LICENSE) into the repo

**Comment by denistwo** [comment]
If I understand the issue right that problem was that I named my license BSD/MIT which makes no sense as this are two different licenses. Therefore, I chose MIT only. Also included the license file.

**Comment by dietmarw** [comment]
The double license was one isssue which you solved now. The other is that you can only simply state what your code is under. So your phrase:

"For our own work MIT License shall apply." just doesn't work. 

Simply state:
"This libary is licensed under the MIT license."
